apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx-config.conf
          readOnly: true
        - name: secret-tls
          mountPath: /etc/nginx/certificate/nginx.crt
          subPath: tls.crt
          readOnly: true
        - name: secret-tls
          mountPath: /etc/nginx/certificate/nginx.key
          subPath: tls.key
          readOnly: true
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: secret-tls
        secret:
          secretName: secret-tls

